server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./database/db_cards
    username: root
    password: example
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: example
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher